/** Pixel map for the adult dragon artwork (faces left). */
export const DRAGON_ROWS = [
  "",
  "",
  "",
  "",
  "",
  "",
  "                                     s",
  "                                     s",
  "                                    sr",
  "                                    sr",
  "                                   srr",
  "                                   rsrs",
  "                                  srsrr",
  "                                 srssrr",
  "                                 srssrr                                          b",
  "                                srsssrr                                          br",
  "                               srrsssmr                                         bbr",
  "                               rrsssmmr                                        mbbr",
  "                              srrsssmmr                                        bbmrr",
  "                             srrsssmmmr                                       mbbmrr",
  "                             rrsssmmmrrs                                      mbbmrr",
  "                            rrrsssmmmrrr                                     mbbbmrrr",
  "                           rrrsssmmmsrrr                                     mbbbmmrr",
  "                          rrrsssmmmsssrr                                    mbbbbmmrr",
  "                         rrrsssmmmssssrr                                    mbbbbmmrrr",
  "                        srrrssmmmsssssrr                                   mbbbbmmmmrr",
  "                       srrrssmmmsssrssrr                                   mbbbbmmmmrrr",
  "                      rrrrsmmmmsssssssrrr                                  bbbbbrmmmmrr",
  "                     rrrrsmmmmssssrsssrrr                                 mbbbbmrmmmmrrr",
  "                    rrrssmmmssssssrsssrrr                                 bbbbbrrmmmmmrr",
  "                   rrrsmmmmssssssrssssrrr                                mbbbbmrrrmmmmrrr",
  "                  rrrsmmmsssssssr       r                                bbbbbmrrrmmmmmrrr",
  "                 rrrmmmsssss          rrr                               mbbbbmmrmrmmmmmmrr",
  "               rrrmmsss            rrr rrr                              mbbbbmrrmrmmmmmmrrr",
  "              rrmss            rr rrr  rrr                             mbbbbbrrrmrrmmmmmmrrr",
  "             mr              rrrrrrr  srrr                             mbbbbmmrrmrrmmmmmmmrr",
  "           rr               rrrrrrr   ssrr                             bbbbbmmrmmrrmmmmmmmmrr",
  "          rss              brrrrrrr   ssrrr                           mbbbbmrmrmmmrmmmmmmmmrrr",
  "        rs                brbbbbrrb   ssrrr                           bbbbbmmmrmmmrrmmmmmmmmrr",
  "                       bbbbbbeebbbb    srrr                          mbbbbbmmmrmmmrrmmmmmmmmmrr",
  "                    bbbbbbbbbbbbbbbb   srrr                          bbbbbmrmmrmmmmrrmmmmmmmmmrr",
  "                  bbbbbbsssssbbbbbbb   ssrrr                         bbbbbmrmmrrmmmrrmmmmmmmmmmrr",
  "                    bssssssssbbbbbbbbb ssrrr                        mbbbbmrmmmrrmmmrrmmmmmmmmmmrr",
  "                       bbbbbbbbbbbbbbbb srrr                        bbbbbmrmmmrrmmmmrrmmmmmmmmmmrr",
  "                     bbb    bbbbbbbbbbb ssrr                       mbbbbmmrmmmrrmmmmrrmmmmmmmmmmmrr",
  "                               brrbbbbbbrrrrr                      bbbbbmmmmmmrrmmmmmrrmmmmmmmmmmmrr",
  "                                 rrrbbbrrrrrr                      bbbbbmrmmmmrrmmmmmrrmmmmmmmmmmmmrr",
  "                                 rrrbbbrrrrrr                     bbbbbmmrmmmmrrmmmmmmrrmmmmmmmmmmmmr",
  "                                 rrrrbbbrsrrrr                    bbbbbmmrmmmmrrmmmmmmrrmmmmmmmmmmmmmr",
  "                                 rrrrbbbrrsrrr                   mbbbbmmrrmmmmrrmmmmmmmrrmmmmmmmmmmmmmr",
  "                                 rrrrbbrrrsrrr                   bbbbbmmrmmmmmrrmmmmmmmrrrmmmmmmmmmmmmrr",
  "                                rrrrrbbrrrssrr                   bbbbmmmrmmmmmrrmmmmmmmmrrmmmmmmmmmmmmmrr",
  "                                rrrrrbbsrssrrrr                 bbbbbmmmrmmmmmrrmmmmmmmmrrrmmmmmmmmmmmmmrr",
  "                                rrrrbbb srrsrrr                 bbbbbmmrrmmmmmrrmmmmmmmmmrrmmmmmmmmmmmmmmr",
  "                               rrrrrbbb rrrssrr                bbbbbmmmrrmmmmmmrrmmmmmmmmmrrmmmmmmmmmmmmmmr",
  "                               rrrrrbbb rrrssrrr               bbbbbmmmrmmmmmmmrrmmmmmmmmmrrmmmmmmmmmmmmmmmr",
  "                               rrrrrbbb  rsssrrr               bbbbmmmmrmmmmmmmrrmmmmmmmmmmrrmmmmmmmmmmmmmmmr",
  "                               rrrrrbbbb ssrrsrrr             bbbbbmmmrrmmmmmmmrrmmmmmmmmmmmrmmmmmmmmmmmmmmmrr",
  "                               rrrrrbbbb  rrrsrrr             bbbbmmmmrrmmmmmmmrrmmmmmmmmmmmrrmmmmmmmmmmmmmmmr",
  "                               rrrrrbbbbb rrrssrrr           bbbbbmmmmrrmmmmmmmmrmmmmmmmmmmmmrmmmmmmmmmmmmmmmmr",
  "                               rrrrrbbbbbbsrsssrrr           bbbbbmmmmrrmmmmmmmmrrmmmmmmmmmmmmrmmmmmmm     mmmmr",
  "                                rrrrrbbbbbbsssrrrr    r     bbbbbmmmmmrmmmmmmmmmrrmmmmmmmmmmmmrmmmmm         mmmr",
  "                                rrrrrbbbbbbbb rrrrr rr      bbbbbmmmmmrmmmmmmmmmrrmmmmmmmmmmmmmrmmmm           mr",
  "                                 rrrrrbbbbbbbbbrsrrrrr      bbbbmmmmmrrmmmmmmmmmmrmmmmmmmmmmmmmmmmm              r",
  "                                 rrrrrrbbbbbbbbbbbbrrrb    bbbbbmmmmmrrmmmmmmmmmmrmmmmmmmmmmmmmmrmm               r",
  "                                  rrrrrrbbbbbbbbbbbbrbbbb  bbbbmmmmmmrrmmmmmmmmmmrrmmmmmmmmmmmmmmm",
  "                                   rrrrrrrbbbbbrbbbbbbbbbbbbbbbmmmmmmrrmmmmmmmmmmrrmmmmmmmm    mmm",
  "                                    rrrrrrrbbbrrrbbbbbbbbbbbbbmmmmmmmrrmmmmmmmmmmmrmmmmmm        m",
  "                                     rrrrrrrrrrrrrbbbbbbbbbbbbmmmmmmmrrmmmmmmmmmmmrmmmmm",
  "                                  rrr  rrrrrrrrrrrbbbbbbsbbbbbmmmmmmmrrmmmmmmmmmmmrrmmmm",
  "                                 rrrrrrrrrrrrrrrrrbbbbbbbssbbbmmmmmmmrrmmmmmmmmmmmmrmmm",
  "                               rrrrrr rrrrrrrrrrrrrrbbbbbbssbbbmmmmmmrrmmmmmmmmmmmmrmmm",
  "                              rrrrrrrr  rrrrrrrrrrrrbbbbbbsssbbmmmmmmrrmmmmmmmmmmmmrmmm",
  "                             rr   rr rr    rr   rrrrbbbbbbssssbmmmmmmrrmmmmmmmmmmmmmrm",
  "                             r    r  rr         rrrrbbbbbbbssssbmmmmmrrmmmmmmm mmmmmrm",
  "                                 r              rrrrbbbbbbbssssbmmmmmrrmmmm       mmrm",
  "                                                rrrrbbbbbbbssssbmmmmmrrmmm          mr",
  "                                                rrrrbbbbbbbssssbmmmmmrrmmm           m",
  "                                                rrrrbbbbbbbssssbmmmmmrrmm",
  "                                                rrrrbbbbbbbssssb mmmmrrm",
  "                                                rrrrbbbbbbbbbssb   mmrrm",
  "                                              ssrrrrbbbbbbbbbbsb    mrrm",
  "                                              ssbrrrbbbbbbbbbbbb     rr",
  "                                             sssbrrrrbbbbbrrbbbb      r",
  "                                             sssbrrrrbbbbrrrbbbb",
  "                                             ssssbrrrbbrrrrbbbbrr",
  "                                             sssssbrbbrrrrrbbbbrrr",
  "                                             ssssssrbbrrrrbbbbrrrrr",
  "                                             sssssssbrrrrrbbbrrrsrrrr",
  "                                              ssssssrrrrrbbbrrrrrssrrr",
  "                                              ssssssrrrrbbbrrrrrrrssrrrr",
  "                                               sssssrrrrbbrrrrrrrrrrssrrr",
  "                                               sssssrrrbbbrrrrrrrrrrrssrrrr",
  "                                              sssss rrrbbb  rrrrrrrrrrsssrrr",
  "                                              sssss rrrbb     rrrrrrrrrrssrrr",
  "                                              sssss  rrbb      rrrrrrrrrrssrrr",
  "                                             sssss   rbbb        rrrrrrrrrrsrrr",
  "                                             sssss   rbbb          rrrrrrrrrsrrr",
  "                                             sssss   rbb             rrrrrrrrssrr",
  "                                            sssss   brbb              rrrrrrrrssr",
  "                                          sssssss  bbrbbb               rrrrrrrsrr",
  "                                       ssssssssss bbbrrbbbb              rrrrrrrsrr",
  "                                    sssssssssssss bbbrrrbbbbb              rrrrrrsr",
  "                                  ssssssssssss ssbbb bbbbbbbbb              rrrrrrsr",
  "                                 ss      sss    sb    bbb   bbb              rrrrrss",
  "                                 s      sss      s     bb    bbb              rrrrrs",
  "                                       s                bb     bb             rrrrrss",
  "                                                         b                     rrrrss",
  "                                                                               rrrrss",
  "                                                                               rrrrss",
  "                                                                               rrrrss",
  "                                                                               rrrrss",
  "                                                                              rrrrsss",
  "                                                                              rrrrssr",
  "                                                                             rrrrsss",
  "                                                                           rrrrrsssr",
  "                                                   r                     rrrrrrsssr",
  "                                                     srr              rrrrrrrrssrr",
  "                                                       rssrrrrrrrrrrrrrrrrrsssrr",
  "                                                           ssssssrrrrrssssssrr",
  "                                                               rrrrrrrrrrr"
];
