/** Authored wyvern pixel map: membrane, shadow, rib, body, and eye. */
export const DRAGON_ROWS = [
  "",
  "",
  "                                                                         rr",
  "                                                                         rr",
  "                                                                        rrr",
  "                                                                       rrmrr",
  "                                 b                                     rrmrr",
  "                                 bb                                   rrmmmrr",
  "                                 bbb                                  rrmmmmrr",
  "                                bbbbb                                rrmmmmmmrr",
  "                                bbbbb                                rrmmmmmmmrr",
  "                               bbsbbbb                               rmmmrrmmmmrrr",
  "                              bbsssbbbb                             rrmmmrrmmmmmrrr",
  "                             bbsssrsbbbb                            rrmmmrmrmmmmmmrrr",
  "                            bbsssrsssbbb                            rrmmrmmrmmmmmmmmrr",
  "                           bbsssrssssssbb                           rmmmrmmrrmmmmmmmmrrr",
  "                          bbsssrrssrrsssbb                         rrmmmrmmmrmmmmmmmmmmrr",
  "                         bbsssrrsssrsssssbb                        rrmmmrmmmrrmmmmmmmmmmrr",
  "                        bbssssrsssrrsssssbb                        rrmmmrmmmmrmmmmmmmmmmmrrr",
  "                       bbssssrssssrrsrrsssbb                       rmmmmrmmmmrrmmmm      mrrr",
  "                      bbssssrrsssrrrsrrssssbb                      rmmmrmmmmmmrmmm         rrr",
  "                     bbsssssrssssrsrsrrrsssbb                     rrmmmrmmmmmmrmm           rrr",
  "                    bbbssssrssssrrrrsrsrssssbb                    rrmmmrmmmmmmrrmb           rr",
  "                   bbbssssrrssssrsrssrsrssssbb                    rrmmmrmmmmmmmr  b",
  "                  bbbsssssrsssssrsrssrsrrssssbb                   rrmmmrmmm    r  bb",
  "                 bbbsssssrrssssrssrssrssrsssssbb                  rmmmmrmm        bbbb",
  "                 bbssssssrsssssrssrssrssrrrsssbb                  rmmmmrmm         bbbb   b",
  "                bbsssssssrssssrrssrssrssrrrrsssbb                 rmmmmrmm         bbbbb bbb",
  "               bbsssssssrsssssrsssrsrrsssrrrsssbb                rrmmmmrm      bb   bbbbbbbbb",
  "              bbssssssssrssssrrsssrsrrsssrrsrsssbb               rrmmmmrm       bbbbbbbbbbbbbb",
  "             bbbsssssssrrssssrssssrsrssssrrsrrssbb               rrmmmmmr       bbbbbbbbbbbbbbbbbb",
  "             bbssssssssrssssrrssssrsrsssssrrsrsssbb              rrmmmmmr       bbbbbbbbbsssssbbbbbbb",
  "            bbsssssssssrssssrsssssrsrsssssrrssrssbb              rrmmmmmr       bbbbbbbbbbbeebbbbbbbbb",
  "           bbsssssssssrrssssrssssrrsrsssssrrssrrssbb             rmmmmmmr       bbbbbbbbbbbbbbbbbbbbb b",
  "           bbsssssssssrssssrsssssrrsrsssssrrsssrssbb            mrmmmmmmr      bbbbbbrbbbbbbbbbbbbbbbbbb",
  "          bbssssssssssrssssrsssssrrsrssssssrsssrrssbb           rrmmmmm        bbbbbrrrbbbb   bbbbbbbbb",
  "         bbsssssssssssrsssrrsssssrrsrssssssrrsssrssbb           rrmmmm         bbbbrrrrrr    bb bbbbbb",
  "         bbssssssssssrssssrssssssrssrssssssrrssssrssbb          rrmmmm    b    bbbrrrrrrrrr  b      b",
  "        bbsssssssssssrsssrrssssssrsrrsssssssrssssrrsbb          rrmmm     bbbbbbbbrrrrrrrrrrr       r",
  "       bbsss      sssrsssrsssssssrsrrsssssssrsssssrssbb         rmmmm     bbbbbbbbrrrr  rrrrrrr  rrr",
  "       bbs          srssrrsssssssrsrssssssssrsssssrrsbb         rmmmm     bbbbbbbbrrrr    rrrrrrrrr",
  "      bb            rrssrssssssssrsrssssssssrrsssssrssbb       rrmmmb     bbbbbbsssssr      rrrrrrr",
  "      bb            rrssrssssssssrsrssssssssrrsssssrrsbb       rrmmmbb    bbbbbbbsrrrr       rrrrr",
  "                    rssrsssssssssrsrsssssssssrssssssrssbb      rrmmmbbb  bbbbbbbrssrrr",
  "                    rssrsssssssssrsrsssssssssrsssssssrsbb      rmmmbbbb bbbbbbsssrsrr",
  "                    rsrrsssssssssrsrsssssssssrrssssssrssbb    rrmmmbbbbbbbbbbbsrrsssr",
  "                    rsrssssssssssrsrsssssssssrrsssssssrsbbbb  rrmmmbbbbbbbbbbrrsrrrr",
  "                    rrrssssssssssrsrsssssssssrrsssssssrssbbbbbbrmbbbbbbbbbbssssrsrrr",
  "                    rrssss    sssrrrssssssssssrssssssssrssbbbbbbbbbbbbbbbbrsrrsssrr",
  "                    rrss        srrrssssssssssrssssssssrssbbbbbbbbbbbbbbbrssrrrrrr",
  "                   rrs           rrsssssssssssrrssssssssrssbbbbbbbbbbbbbrrsrrrrr",
  "                   rr            rrsssssssssssrrssssssssrssbbbbbbbbbbbbrrrsrrrr",
  "                                 rrsssssssssssrrsssssssssrsbbbbbbbbbbbrrrsrrrr",
  "                                 rrsssssssssssrrsssssssssrbbbbbbbbbbbbrrrsrrr",
  "                                 rrssssssssssssrsssssssssbbbbbbbbbbbbbrrsrrr",
  "                                 rrssssssssssssrsssssssssbbbbbbbbbbbbbrrsrrr",
  "                                 rrssss       srrsssssssbbbbbbbbbbbbbrrrsrr",
  "                                 rrss          rrssssssbbbbbbbbbbbbbbrrsrrr",
  "                                 rr            rrssssssbbbbbbbbbbbbbrrrsrrr",
  "                                                rssssssbbbbbbbbbbbbrrrsrrrr",
  "                                                rsssssbbbbbbbbbbbrrrrrsrrrr",
  "                                                rssss bbbbbbbbbbrrrrrssrrr",
  "                                                rss   bbbbbbbbrrrrrrrsrrrr",
  "                                                rr    bbbbbbbrrrrrrrrsrrrr",
  "                                                      bbbbbbbbrrrrrrsrrrrrr",
  "                                                       bbbbbbbrrrrssrrrrrrr",
  "                                                       bbbbbbbbrsssrrrrrrrrr",
  "                                                       bbbbbbbbsrrrrrrrrrrrr",
  "                                                      bbbbbbbbrrrrrrrrrrrrrr",
  "                                                      bbbbbbbbrrrr    rrrrrr",
  "                                                     bbbbbbbbrrrr    rrrrrrr",
  "                                                    bbbbbbbbrrrr     rrrrrr",
  "                                                    bbbbbbbbrrrr     rrrrrr",
  "                                                   bbbbbbbbrrrr     rrrrrr",
  "                                                  bbbbbbbbrrrr      rrrrr",
  "                                                  bbbbbbbrrrr      rrrrrr",
  "                                                 rbbbbbbrrrr       rrrrr",
  "                                                rrrbbbbbbrr        rrrr",
  "                                               rrrrbbbbbb         rrrrrrrr",
  "                                              rrrrrbbbbbb         rrrrrrrrrrr",
  "                                             rrrrrbrbbbbbb         rrrrrrrrrrr",
  "                                            rrrrbbrbbbbbbb             rrrrrrrr",
  "                                            rrrbbbbbbbbbbbb            rrr  r rr",
  "                                           rrrbrbbbbbbbbbb                  r",
  "                                          rrrbrrbb   bbbb b",
  "                                          rrbrrbb    bb   b",
  "                                         rrbbrrb     bb",
  "                                         rrbrrr",
  "                                        rrbrrr",
  "                                        rrbrrr",
  "                                        rrbrr",
  "                                        rrbrr",
  "                                        rbrrr",
  "                                        rbrrr",
  "                                        rrbrr",
  "                                         rbrrr",
  "                                         rbbrrr",
  "                                          rbbrrr",
  "                                           rbbrrrr",
  "                                            rrbbrrrrrr       rr",
  "                                              rrbbbbrrrrrbbbbb",
  "                                                 rrrbbbbb",
];
