/** Authored wyvern pixel map (faces left): membrane, shadow, rib, body, and eye.
 *  Right-facing original: `./dragon-art-right`.
 */
export const DRAGON_ROWS = [
  "",
  "",
  "                             rr",
  "                             rr",
  "                             rrr",
  "                            rrmrr",
  "                            rrmrr                                     b",
  "                           rrmmmrr                                   bb",
  "                          rrmmmmrr                                  bbb",
  "                         rrmmmmmmrr                                bbbbb",
  "                        rrmmmmmmmrr                                bbbbb",
  "                      rrrmmmmrrmmmr                               bbbbsbb",
  "                     rrrmmmmmrrmmmrr                             bbbbsssbb",
  "                   rrrmmmmmmrmrmmmrr                            bbbbsrsssbb",
  "                  rrmmmmmmmmrmmrmmrr                            bbbsssrsssbb",
  "                rrrmmmmmmmmrrmmrmmmr                           bbssssssrsssbb",
  "               rrmmmmmmmmmmrmmmrmmmrr                         bbsssrrssrrsssbb",
  "              rrmmmmmmmmmmrrmmmrmmmrr                        bbsssssrsssrrsssbb",
  "            rrrmmmmmmmmmmmrmmmmrmmmrr                        bbsssssrrsssrssssbb",
  "           rrrm      mmmmrrmmmmrmmmmr                       bbsssrrsrrssssrssssbb",
  "          rrr         mmmrmmmmmmrmmmr                      bbssssrrsrrrsssrrssssbb",
  "         rrr           mmrmmmmmmrmmmrr                     bbsssrrrsrsrssssrsssssbb",
  "         rr           bmrrmmmmmmrmmmrr                    bbssssrsrsrrrrssssrssssbbb",
  "                     b  rmmmmmmmrmmmrr                    bbssssrsrssrsrssssrrssssbbb",
  "                    bb  r    mmmrmmmrr                   bbssssrrsrssrsrsssssrsssssbbb",
  "                  bbbb        mmrmmmmr                  bbsssssrssrssrssrssssrrsssssbbb",
  "             b   bbbb         mmrmmmmr                  bbsssrrrssrssrssrsssssrssssssbb",
  "            bbb bbbbb         mmrmmmmr                 bbsssrrrrssrssrssrrssssrsssssssbb",
  "           bbbbbbbbb   bb      mrmmmmrr                bbsssrrrsssrrsrsssrsssssrsssssssbb",
  "          bbbbbbbbbbbbbb       mrmmmmrr               bbsssrsrrsssrrsrsssrrssssrssssssssbb",
  "      bbbbbbbbbbbbbbbbbb       rmmmmmrr               bbssrrsrrssssrsrssssrssssrrsssssssbbb",
  "   bbbbbbbsssssbbbbbbbbb       rmmmmmrr              bbsssrsrrsssssrsrssssrrssssrssssssssbb",
  "  bbbbbbbbbeebbbbbbbbbbb       rmmmmmrr              bbssrssrrsssssrsrsssssrssssrsssssssssbb",
  " b bbbbbbbbbbbbbbbbbbbbb       rmmmmmmr             bbssrrssrrsssssrsrrssssrssssrrsssssssssbb",
  "bbbbbbbbbbbbbbbbbbrbbbbbb      rmmmmmmrm            bbssrsssrrsssssrsrrsssssrssssrsssssssssbb",
  " bbbbbbbbb   bbbbrrrbbbbb        mmmmmrr           bbssrrsssrssssssrsrrsssssrssssrssssssssssbb",
  "  bbbbbb bb    rrrrrrbbbb         mmmmrr           bbssrsssrrssssssrsrrsssssrrsssrsssssssssssbb",
  "   b      b  rrrrrrrrrbbb    b    mmmmrr          bbssrssssrrssssssrssrssssssrssssrssssssssssbb",
  "   r       rrrrrrrrrrrbbbbbbbb     mmmrr          bbsrrssssrsssssssrrsrssssssrrsssrsssssssssssbb",
  "    rrr  rrrrrrr  rrrrbbbbbbbb     mmmmr         bbssrsssssrsssssssrrsrsssssssrsssrsss      sssbb",
  "     rrrrrrrrr    rrrrbbbbbbbb     mmmmr         bbsrrsssssrssssssssrsrsssssssrrssrs          sbb",
  "     rrrrrrr      rsssssbbbbbb     bmmmrr       bbssrsssssrrssssssssrsrssssssssrssrr            bb",
  "      rrrrr       rrrrsbbbbbbb    bbmmmrr       bbsrrsssssrrssssssssrsrssssssssrssrr            bb",
  "                  rrrssrbbbbbbb  bbbmmmrr      bbssrssssssrsssssssssrsrsssssssssrssr",
  "                   rrsrsssbbbbbb bbbbmmmr      bbsrsssssssrsssssssssrsrsssssssssrssr",
  "                   rsssrrsbbbbbbbbbbbmmmrr    bbssrssssssrrsssssssssrsrsssssssssrrsr",
  "                    rrrrsrrbbbbbbbbbbmmmrr  bbbbsrsssssssrrsssssssssrsrssssssssssrsr",
  "                    rrrsrssssbbbbbbbbbbmrbbbbbbssrsssssssrrsssssssssrsrssssssssssrrr",
  "                     rrsssrrsrbbbbbbbbbbbbbbbbssrssssssssrssssssssssrrrsss    ssssrr",
  "                      rrrrrrssrbbbbbbbbbbbbbbbssrssssssssrssssssssssrrrs        ssrr",
  "                        rrrrrsrrbbbbbbbbbbbbbssrssssssssrrsssssssssssrr           srr",
  "                         rrrrsrrrbbbbbbbbbbbbssrssssssssrrsssssssssssrr            rr",
  "                          rrrrsrrrbbbbbbbbbbbsrsssssssssrrsssssssssssrr",
  "                           rrrsrrrbbbbbbbbbbbbrsssssssssrrsssssssssssrr",
  "                            rrrsrrbbbbbbbbbbbbbsssssssssrssssssssssssrr",
  "                            rrrsrrbbbbbbbbbbbbbsssssssssrssssssssssssrr",
  "                             rrsrrrbbbbbbbbbbbbbsssssssrrs       ssssrr",
  "                             rrrsrrbbbbbbbbbbbbbbssssssrr          ssrr",
  "                             rrrsrrrbbbbbbbbbbbbbssssssrr            rr",
  "                             rrrrsrrrbbbbbbbbbbbbssssssr",
  "                             rrrrsrrrrrbbbbbbbbbbbsssssr",
  "                              rrrssrrrrrbbbbbbbbbb ssssr",
  "                              rrrrsrrrrrrrbbbbbbbb   ssr",
  "                              rrrrsrrrrrrrrbbbbbbb    rr",
  "                             rrrrrrsrrrrrrbbbbbbbb",
  "                             rrrrrrrssrrrrbbbbbbb",
  "                            rrrrrrrrrsssrbbbbbbbb",
  "                            rrrrrrrrrrrrsbbbbbbbb",
  "                            rrrrrrrrrrrrrrbbbbbbbb",
  "                            rrrrrr    rrrrbbbbbbbb",
  "                            rrrrrrr    rrrrbbbbbbbb",
  "                             rrrrrr     rrrrbbbbbbbb",
  "                             rrrrrr     rrrrbbbbbbbb",
  "                              rrrrrr     rrrrbbbbbbbb",
  "                               rrrrr      rrrrbbbbbbbb",
  "                               rrrrrr      rrrrbbbbbbb",
  "                                rrrrr       rrrrbbbbbbr",
  "                                 rrrr        rrbbbbbbrrr",
  "                              rrrrrrrr         bbbbbbrrrr",
  "                           rrrrrrrrrrr         bbbbbbrrrrr",
  "                          rrrrrrrrrrr         bbbbbbrbrrrrr",
  "                         rrrrrrrr             bbbbbbbrbbrrrr",
  "                        rr r  rrr            bbbbbbbbbbbbrrr",
  "                           r                  bbbbbbbbbbrbrrr",
  "                                             b bbbb   bbrrbrrr",
  "                                             b   bb    bbrrbrr",
  "                                                 bb     brrbbrr",
  "                                                         rrrbrr",
  "                                                          rrrbrr",
  "                                                          rrrbrr",
  "                                                           rrbrr",
  "                                                           rrbrr",
  "                                                           rrrbr",
  "                                                           rrrbr",
  "                                                           rrbrr",
  "                                                          rrrbr",
  "                                                         rrrbbr",
  "                                                        rrrbbr",
  "                                                      rrrrbbr",
  "                                         rr       rrrrrrbbrr",
  "                                          bbbbbrrrrrbbbbrr",
  "                                               bbbbbrrr",
];
